version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
       - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 13.93.104.78
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "daf-iot-events:1:1"

  trifecta:
    image: janschultecom/docker-trifecta
    ports:
      - "80:9000" 
    volumes: 
      - ./trifecta-decoders:/home/trifecta/.trifecta/decoders
    environment:
      ZK_HOST: zookeeper:2181
